#!/bin/sh

usage='USAGE: simbar --print|--xsetroot --once|--repeat [--config /path/to/config] [--delimiter DEL]'

#
# defaults
#

config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/simbar"
config_dir="./config"
delimiter=' '
esc_char="$(printf '\037')"

#
# user input
#

multiple_freq_modes() {
	echo 'ERROR: You cannot set multiple frequency modes!' >&2
	echo $usage >&2
}

for arg in "$@"; do
	if [ "$next_is_config" ]; then
		config_dir="$arg"
		next_is_config=''
	elif [ "$next_is_update" ]; then
		if [ "$arg" -eq "$arg" ]; then
			update_freq="$arg"
		else
			echo "ERROR: Not a number: $arg" >&2
			exit 1
		fi
		next_is_update=''
	elif [ "$next_is_delimiter" ]; then
		delimiter="$arg"
		next_is_delimiter=''
	else
		case "$arg" in
			'-p'|'--print')
				print_mode='print'
				;;
			'-x'|'--xsetroot')
				xsetroot_mode='xsetroot'
				;;
			'-o'|'--once')
				[ -z "$freq_mode" ] && freq_mode='once' || multiple_freq_modes
				;;
			'-r'|'--repeat')
				[ -z "$freq_mode" ] && freq_mode='repeat' || multiple_freq_modes
				;;
			'-c'|'--config')
				next_is_config=1
				;;
			'-d'|'--delimiter')
				next_is_delimiter=1
				;;
			'-h'|'--help')
				echo $usage
				exit 0
				;;
			*)
				echo "ERROR: Unknown argument: $arg" >&2
				echo $usage >&2
				exit 1
				;;
		esac
	fi
done

if [ -z "$print_mode" ] && [ -z "$xsetroot_mode" ]; then
	echo 'ERROR: You have to pass an output mode!' >&2
	echo $usage >&2
	exit 1
fi

if [ -z "$freq_mode" ]; then
	echo 'ERROR: You have to pass a frequency mode!' >&2
	echo $usage >&2
	exit 1
fi

wrap_into_colors() {
	content=$1
	fg=$2
	bg=$3

	wrapped="$content"

	if [ "$fg" ]; then
		wrapped="^c$fg^$wrapped"
	fi

	if [ "$bg" ]; then
		wrapped="^b$bg^$wrapped"
	fi

	if [ "$fg" ] || [ "$bg" ]; then
		wrapped="$wrapped^d^"
	fi

	printf "$wrapped"

}

cache_module() {
	mod=$1

	mod_regex="$(printf "$mod" | sed 's/\//\\\//g')"

	cache="$(printf "$cache" | sed "/^$mod_regex/d")"
	cache="$cache\n$mod$esc_char$($mod)"
}

get_value_from_cache() {
	mod=$1

	mod_regex="$(printf "$mod" | sed 's/\//\\\//g')"

	printf "$cache" | grep "^$mod_regex" | cut -d"$esc_char" -f2
}

generate_bar() {
	sec=$1

	bar=''

	# load modules.conf
	if ! [ -f "$config_dir/modules.conf" ]; then
		echo "ERROR: No config file found: $config_dir/modules.conf" >&2
		exit 1
	fi
	config="$(cat "$config_dir/modules.conf")"

	IFS=$'
'
	for line in $config; do
		mod="$config_dir/modules/$(echo $line | cut -d' ' -f1)"
		update_freq="$(echo $line | cut -d' ' -f2)"
		fg="$(printf $line | cut -d' ' -f3)"
		bg="$(printf $line | cut -d' ' -f4)"

		if [ $update_freq -ge 1 ] && [ $(($sec % $update_freq)) -eq 0 ]; then
			cache_module "$mod"
		else
			printf "$cache" | grep -q "^$mod" || cache_module "$mod"
		fi

		out="$(wrap_into_colors "$(get_value_from_cache "$mod")" "$fg" "$bg")"
		[ "$bar" ] && bar="$bar\n$out" || bar="$out"
	done

	bar="$(printf "$bar" | tr '\n' "$esc_char" | sed "s/$esc_char/$delimiter/g")"
}

#
# main
#

if [ "$freq_mode" = 'once' ]; then
	generate_bar 0
	if [ "$print_mode" ]; then
		printf "$bar"
	fi

	if [ "$xsetroot_mode" ]; then
		xsetroot -name "$bar"
	fi
elif [ "$freq_mode" = 'repeat' ]; then
	sec=0
	while true; do
		generate_bar "$sec"

		if [ "$print_mode" ]; then
			echo "$bar"
		fi

		if [ "$xsetroot_mode" ]; then
			xsetroot -name "$bar"
		fi

		sleep 1
		sec=$((sec + 1))
	done
fi
