#!/bin/sh

connection=$(nmcli -a | grep 'Wired' | awk 'NR == 1 {print $1; exit}')
[ -z $connection ] && connection=$(nmcli -t -f active,ssid dev wifi | grep -m 1 '^yes' | cut -c 5-)
[ -z $connection ] && connection='Off'

printf "$connection"
