delimiter = " | "
padding = true

[[module]]
cmd = "./modules/whoami"

[[module]]
cmd = "./modules/network"
repeat = 15
fg = "#FF0000"
bg = "#000000"

[[module]]
cmd = "./modules/memory"
repeat = 10
fg = "xresources"
bg = "xresources"

[[module]]
cmd = "date '+%a %Y-%m-%d %R:%S'"
repeat = 5
fg = "#fff00f"
