delimiter = " " # default is " | "
padding = true # default is false

[[module]]
# name is *not* optional and should be unique
name = "whoami"

# cmd is *not* optional
# the value is executed as `/bin/sh -c VALUE`
# note that you cannot use spaces currently, so only simple commands are possible
cmd = "whoami"

[[module]]
name = "network"

# if you pass a relative path,
# the cmd gets executed from the location of the config file
cmd = "./modules/network"

# using repeat you can specify how often (in secs) the cmd should be repeated
# if repeat is not specified, the cmd gets executed only in the first second
repeat = 15

# you can specify colors like this
fg = "#FF0000"
bg = "#000000"

[[module]]
name = "memory"
cmd = "./modules/memory"
repeat = 10

# you can pass "xresources" to search in the XRDB for a color
fg = "xresources" # this searches for "simbar.memory.fg"
bg = "xresources" # this searches for "simbar.memory.bg"

[[module]]
name = "date"
cmd = "date"
repeat = 5

# you can specify a prefix and a suffix
prefix = "[DATE: "
suffix = "]"

fg = "#fff00f"
